import { chromium } from 'playwright'; import http from 'http'; import fs from 'fs'; import zlib from 'zlib';
const D='/private/tmp/claude-501/-Users-mayu-Projects-tesserix-beautyandcruor/a0481450-8f38-4875-a9b0-8e39b1b5a8cd/scratchpad';
const gz=zlib.gzipSync(fs.readFileSync(D+'/wrap.html'),{level:9});
const srv=http.createServer((q,r)=>{r.writeHead(200,{'content-type':'text/html; charset=utf-8','content-encoding':'gzip','cache-control':'no-store'});r.end(gz);});
await new Promise(r=>srv.listen(8788,r));
const b=await chromium.launch();
const ctx=await b.newContext({viewport:{width:390,height:844},deviceScaleFactor:2,isMobile:true,hasTouch:true});
const p=await ctx.newPage(); const cdp=await ctx.newCDPSession(p);
await p.addInitScript(()=>{ window.__v={lcp:0,cls:0,lt:[],lcpEl:''};
  new PerformanceObserver(l=>{const e=l.getEntries();const x=e[e.length-1];window.__v.lcp=Math.round(x.startTime);window.__v.lcpEl=(x.element&&(x.element.tagName+'.'+x.element.className))||x.url||'?';}).observe({type:'largest-contentful-paint',buffered:true});
  new PerformanceObserver(l=>{l.getEntries().forEach(e=>{if(!e.hadRecentInput)window.__v.cls+=e.value;});}).observe({type:'layout-shift',buffered:true});
  new PerformanceObserver(l=>{l.getEntries().forEach(e=>window.__v.lt.push(Math.round(e.duration)));}).observe({type:'longtask',buffered:true});
});
await cdp.send('Network.enable');
await cdp.send('Network.emulateNetworkConditions',{offline:false,downloadThroughput:1.6*1024*1024/8,uploadThroughput:750*1024/8,latency:150,connectionType:'cellular4g'});
await cdp.send('Emulation.setCPUThrottlingRate',{rate:4});
await p.goto('http://127.0.0.1:8788/',{waitUntil:'load',timeout:180000});
await p.waitForTimeout(6000);
const v=await p.evaluate(()=>{const n=performance.getEntriesByType('navigation')[0];
 const fcp=performance.getEntriesByName('first-contentful-paint')[0];
 const tbt=window.__v.lt.reduce((s,d)=>s+Math.max(0,d-50),0);
 return {FCP:fcp?Math.round(fcp.startTime):null, LCP:window.__v.lcp, LCPelement:window.__v.lcpEl, CLS:+window.__v.cls.toFixed(4),
  longTasks:window.__v.lt, TBT:tbt, responseEnd:Math.round(n.responseEnd), DCL:Math.round(n.domContentLoadedEventEnd), transferKB:Math.round(n.transferSize/1024)};});
console.log('=== Lighthouse-mobile-equivalent throttling (1.6Mbps / 150ms RTT / 4x CPU) ===');
console.log(JSON.stringify(v,null,1));
const score=(val,p10,med)=>{ // lighthouse log-normal
  const mu=Math.log(med), sigma=Math.abs(Math.log(med)-Math.log(p10))/(Math.SQRT2*0.9061938024368232);
  const erfc=x=>{const z=Math.abs(x),t=1/(1+z/2),r=t*Math.exp(-z*z-1.26551223+t*(1.00002368+t*(0.37409196+t*(0.09678418+t*(-0.18628806+t*(0.27886807+t*(-1.13520398+t*(1.48851587+t*(-0.82215223+t*0.17087277)))))))));return x>=0?r:2-r;};
  return Math.round(100*(erfc((Math.log(val)-mu)/(sigma*Math.SQRT2))/2));};
console.log('\n=== approximate Lighthouse v10/11 mobile metric scores ===');
console.log('  FCP ',v.FCP,'ms  -> score',score(v.FCP,1800,3000),' (weight 10%)');
console.log('  LCP ',v.LCP,'ms  -> score',score(v.LCP,2500,4000),' (weight 25%)');
console.log('  TBT ',v.TBT,'ms  -> score',v.TBT<=0?100:score(Math.max(v.TBT,1),200,600),' (weight 30%)');
console.log('  CLS ',v.CLS,'     -> score',v.CLS<=0.1?100:score(Math.max(v.CLS,.001),0.1,0.25),' (weight 25%)');
console.log('  (Speed Index 10% — not measurable here, but the viewport is black chrome-only until ~9s so it will be near 0)');
const s=(w,x)=>w*x;
const total=Math.round(s(.10,score(v.FCP,1800,3000))+s(.25,score(v.LCP,2500,4000))+s(.30,v.TBT<=0?100:score(Math.max(v.TBT,1),200,600))+s(.25,v.CLS<=0.1?100:score(Math.max(v.CLS,.001),0.1,0.25))+s(.10,5));
console.log('  --> weighted estimate (SI assumed ~5):', total, '/100   [target 95+]');
await b.close(); srv.close();
