import galleries from "@/content/galleries.json";
import curation from "@/content/curation.json";
import { keyForSource } from "@/lib/images";

/**
 * Which images belong to which discipline, and in what order.
 *
 * Two different questions, answered by two different files, on purpose.
 *
 * MEMBERSHIP is galleries.json, generated by scripts/organize.mjs from the
 * live-site crawl. That is the rights answer — only images she actually
 * published get in — and it is not a judgement anyone should be editing by
 * hand.
 *
 * ORDER is curation.json, hand-authored. Which frames lead a gallery, what the
 * homepage opens on, which plate each discipline shows. Deriving that from the
 * old WordPress homepage produced a behind-the-scenes film-set photo, a beard
 * trim and some plaster hands in place of the character builds the design was
 * built around.
 *
 * Order is applied HERE, at build time, rather than baked into galleries.json
 * by organize.mjs. Both produce the same result — verified against the
 * committed file, which this reproduces exactly — but organize.mjs needs the
 * image originals and rewrites public/img, so it only runs on a laptop. An
 * edit to curation.json had no effect on the deployed site until it did, which
 * makes the file's own promise — "an admin UI, if one is ever built, writes
 * this file and nothing else changes" — false. Applying it at build time makes
 * it true: curation.json is now a content file like credits.json, and a commit
 * to it ships.
 *
 * TODO(client): membership is still OUR selection from the 290 recovered
 * originals, made by eye off contact sheets. Parimiti has not confirmed it,
 * and the library mixes portfolio work with behind-the-scenes and phone
 * snapshots.
 */
type GalleryFile = Record<string, string[] | Record<string, string>>;
const G = galleries as GalleryFile;

type Curation = {
  hero?: string[];
  leads?: Record<string, string[]>;
  covers?: Record<string, string>;
  artist?: string;
};
const C = curation as Curation;

const list = (k: string): string[] => {
  const v = G[k];
  return Array.isArray(v) ? v : [];
};

/** Curated upload paths to manifest keys, dropping any not in this build. */
const resolve = (paths: string[] | undefined): string[] => {
  const keys: string[] = [];
  for (const path of paths ?? []) {
    const key = keyForSource(path);
    if (key && !keys.includes(key)) keys.push(key);
  }
  return keys;
};

export const GALLERY_BY_SLUG: Record<string, string> = {
  "sfx-prosthetics": "sfx",
  "casting-sculpting": "casting",
  "film-television": "film",
  "editorial-fashion": "editorial",
};

/**
 * A discipline's images: its curated leads first, in the order given, then
 * everything else in the order the crawl found it.
 */
export function galleryFor(slug: string): string[] {
  const name = GALLERY_BY_SLUG[slug];
  if (!name) return [];
  const members = list(name);
  const leads = resolve(C.leads?.[name]).filter((k) => members.includes(k));
  return [...leads, ...members.filter((k) => !leads.includes(k))];
}

/**
 * The homepage opening reel. Entirely curated — the strongest character work,
 * not one image per discipline. Spreading it across categories diluted the
 * opening, and the discipline strips below already carry the range.
 */
export function heroKeys(): string[] {
  const curated = resolve(C.hero);
  return curated.length ? curated : list("hero");
}

export function artistPortrait(): string | null {
  return (C.artist ? keyForSource(C.artist) : null) ?? list("artist")[0] ?? null;
}

/**
 * The image on a discipline's plate on the homepage.
 *
 * Kept separate from `leads` because the plate and the gallery's first frame
 * are different jobs: the plate has to read at a glance behind a title, the
 * first frame opens a sequence. Falls back to the gallery's lead, so an unset
 * cover degrades to a sensible image rather than to whatever sorted first.
 */
export function coverFor(slug: string): string | null {
  const path = C.covers?.[slug];
  return (path ? keyForSource(path) : null) ?? galleryFor(slug)[0] ?? null;
}

/** How many of a discipline's works preview on the homepage. */
export const PREVIEW_COUNT = 6;
