import type { NextConfig } from "next";

const nextConfig: NextConfig = {
  // Fully static: no Node process at runtime, served by nginx.
  output: "export",

  // The old WordPress URLs all carry a trailing slash and must be preserved.
  // With output:export this also makes Next emit /about-me/index.html rather
  // than /about-me.html, which is what the nginx config below expects.
  trailingSlash: true,

  // No runtime optimiser exists in a static export. Every derivative is
  // pre-generated by scripts/images.mjs and read from src/generated/images.json,
  // so next/image must not try to optimise anything.
  images: { unoptimized: true },

  reactStrictMode: true,
  // Next 16 no longer accepts `eslint`/`typescript` blocks here; both already
  // fail the build by default, which is what we want.
};

export default nextConfig;
