{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "beautyandcruor.serviceAccountName" . }}
  labels:
    {{- include "beautyandcruor.labels" . | nindent 4 }}
automountServiceAccountToken: false
{{- end }}
