package main

// Session authentication for the admin.
//
// ONE SHARED PASSWORD, deliberately. There is one person who edits this site.
// Standing up an identity provider, or a user table, for one account is more
// moving parts to hold correct than the thing it protects — and every one of
// them is another place a mistake locks her out of her own portfolio.
//
// The password is never stored. ADMIN_PASSWORD_HASH holds a PBKDF2-SHA256
// verifier, generated by `enquiry -hash`, and the hash is what lives in Secret
// Manager. Someone reading the secret learns nothing they can type into the
// login form without spending the iterations.
//
// crypto/pbkdf2 is standard library as of Go 1.24, so this costs no
// dependency. go.sum stays empty, which is the property that makes this image
// a `scratch` container with one binary in it.

import (
	"crypto/hmac"
	"crypto/pbkdf2"
	"crypto/rand"
	"crypto/sha256"
	"crypto/subtle"
	"encoding/base64"
	"fmt"
	"net/http"
	"strconv"
	"strings"
	"time"
)

const (
	// Cost. 600k is the OWASP figure for PBKDF2-SHA256, and this runs once per
	// login on a pod that is otherwise idle, so there is no reason to go lower.
	pbkdf2Iterations = 600_000
	pbkdf2KeyLen     = 32
	saltLen          = 16

	sessionCookie = "bac_admin"
	sessionTTL    = 8 * time.Hour
	// Logins per address per hour. A person who has genuinely forgotten which
	// password it is gets several attempts; a script gets almost none.
	loginAttempts = 8
)

// verifier is the parsed form of ADMIN_PASSWORD_HASH.
type verifier struct {
	iterations int
	salt       []byte
	hash       []byte
}

// encodeVerifier renders a verifier as the single string that goes in the
// secret: pbkdf2-sha256$<iterations>$<salt>$<hash>, both fields base64.
func encodeVerifier(v verifier) string {
	return fmt.Sprintf("pbkdf2-sha256$%d$%s$%s",
		v.iterations,
		base64.RawStdEncoding.EncodeToString(v.salt),
		base64.RawStdEncoding.EncodeToString(v.hash),
	)
}

func parseVerifier(s string) (verifier, error) {
	parts := strings.Split(strings.TrimSpace(s), "$")
	if len(parts) != 4 || parts[0] != "pbkdf2-sha256" {
		return verifier{}, fmt.Errorf("want pbkdf2-sha256$iterations$salt$hash, got %d field(s)", len(parts))
	}
	iter, err := strconv.Atoi(parts[1])
	if err != nil || iter < 1 {
		return verifier{}, fmt.Errorf("iterations: %q", parts[1])
	}
	salt, err := base64.RawStdEncoding.DecodeString(parts[2])
	if err != nil {
		return verifier{}, fmt.Errorf("salt: %w", err)
	}
	hash, err := base64.RawStdEncoding.DecodeString(parts[3])
	if err != nil {
		return verifier{}, fmt.Errorf("hash: %w", err)
	}
	if len(salt) == 0 || len(hash) == 0 {
		return verifier{}, fmt.Errorf("empty salt or hash")
	}
	return verifier{iterations: iter, salt: salt, hash: hash}, nil
}

// newVerifier derives a fresh verifier for a password. Used by `-hash`.
func newVerifier(password string) (verifier, error) {
	salt := make([]byte, saltLen)
	if _, err := rand.Read(salt); err != nil {
		return verifier{}, err
	}
	return deriveVerifier(password, salt, pbkdf2Iterations)
}

// deriveVerifier builds a verifier with explicit parameters.
//
// Separate from newVerifier so tests can use a cheap cost: 600k iterations is
// the whole point in production and far too slow to run per test case.
func deriveVerifier(password string, salt []byte, iterations int) (verifier, error) {
	key, err := pbkdf2.Key(sha256.New, password, salt, iterations, pbkdf2KeyLen)
	if err != nil {
		return verifier{}, err
	}
	return verifier{iterations: iterations, salt: salt, hash: key}, nil
}

// matches reports whether password derives this verifier's hash.
//
// Constant time, so a wrong password cannot be narrowed down by how long the
// comparison took. The derivation itself dominates anyway.
func (v verifier) matches(password string) bool {
	key, err := pbkdf2.Key(sha256.New, password, v.salt, v.iterations, len(v.hash))
	if err != nil {
		return false
	}
	return subtle.ConstantTimeCompare(key, v.hash) == 1
}

// --- sessions ---------------------------------------------------------------
//
// A session is its own expiry plus an HMAC of it. Nothing is stored server
// side: there is one user, so a session carries no identity, only "this
// browser proved it knew the password, and until when".
//
// That also means a restart does not sign everyone out, and two replicas do
// not need shared state — neither matters today with one pod, but the
// alternative is a store to keep correct for no benefit.

type sessions struct {
	key []byte
}

func (s sessions) issue(now time.Time) string {
	expiry := strconv.FormatInt(now.Add(sessionTTL).Unix(), 10)
	return expiry + "." + s.sign(expiry)
}

func (s sessions) sign(payload string) string {
	mac := hmac.New(sha256.New, s.key)
	mac.Write([]byte(payload))
	return base64.RawURLEncoding.EncodeToString(mac.Sum(nil))
}

// valid reports whether a cookie value is one we issued and has not expired.
func (s sessions) valid(value string, now time.Time) bool {
	expiry, sig, ok := strings.Cut(value, ".")
	if !ok {
		return false
	}
	// Signature first: an unsigned value must not be able to probe anything,
	// including whether a given expiry would have been accepted.
	if !hmac.Equal([]byte(sig), []byte(s.sign(expiry))) {
		return false
	}
	unix, err := strconv.ParseInt(expiry, 10, 64)
	if err != nil {
		return false
	}
	return now.Before(time.Unix(unix, 0))
}

func (s sessions) cookie(value string, now time.Time) *http.Cookie {
	c := &http.Cookie{
		Name:     sessionCookie,
		Value:    value,
		Path:     "/",
		HttpOnly: true,
		// The admin is only ever reached over TLS through the gateway.
		Secure: true,
		// Strict, not Lax: nothing off-site should ever navigate into an
		// authenticated admin action. This is also the first of the two CSRF
		// defences — see the token in admin.go for the second.
		SameSite: http.SameSiteStrictMode,
		Expires:  now.Add(sessionTTL),
	}
	if value == "" {
		c.Expires = time.Unix(0, 0)
		c.MaxAge = -1
	}
	return c
}
